<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerETQ6hVA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerETQ6hVA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerETQ6hVA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerETQ6hVA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerETQ6hVA\App_KernelDevDebugContainer([
    'container.build_hash' => 'ETQ6hVA',
    'container.build_id' => 'cf311460',
    'container.build_time' => 1673107087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerETQ6hVA');
