<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIblQNoP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIblQNoP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIblQNoP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIblQNoP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIblQNoP\App_KernelDevDebugContainer([
    'container.build_hash' => 'IblQNoP',
    'container.build_id' => 'aa3eb894',
    'container.build_time' => 1673105119,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIblQNoP');
