<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNcJewMR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNcJewMR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNcJewMR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNcJewMR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNcJewMR\App_KernelDevDebugContainer([
    'container.build_hash' => 'NcJewMR',
    'container.build_id' => '0b4c80b2',
    'container.build_time' => 1673103585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNcJewMR');
